### ISSUE TITLE
I have met this error when run train.py

### ISSUE THREAD

**Issue by bemoregt** [oyxhust/wgan-gp-anomaly#1]
Hi, @oyxhust 

I have met this error when train time.
-------------------------------------------
model [WGAN_GP_Model] was created
create web directory ./checkpoints/mnist/web...
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    model.optimize_parameters(only_update_D)
  File "/Users/kerbal/wgan-gp-anomaly/models/wgan_gp_model.py", line 153, in optimize_parameters
    self.update_D()
  File "/Users/kerbal/wgan-gp-anomaly/models/wgan_gp_model.py", line 99, in update_D
    self.real_data_v = Variable(real_data)
UnboundLocalError: local variable 'real_data' referenced before assignment
------------------------------------------------------------

My Command: 
$ python3 train.py --dataroot ./datasets/MNIST/ --name mnist --gpu_ids -1 --no_flip

What's wrong with me?

MacOSX High Sierra, CPU Only, Python3.6, PyTorch 0.3.x

Thanks in advance.

**Comment by bemoregt** [comment]
Hi, @oyxhust 

I fixed it using CUDA machine.

**Comment by ZhuFeii** [comment]
Hi，@bemoregt   
I encountered the same situation as you. Could you explain how to fix it, pls ?
